import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./app.css";
import AuthenticatorWrapper from "./AuthenticatorWrapper";
import Sidebar from "./components/Sidebar";
import "./components/sidebar.module.css";
import "@aws-amplify/ui-react/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mapping Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthenticatorWrapper>
          <div style={{ display: "flex" }}>
            <Sidebar />
            <div style={{ flex: 1, marginLeft: 220, padding: "1rem" }}>
              {children}
            </div>
          </div>
        </AuthenticatorWrapper>
      </body>
    </html>
  );
}
